### PR TITLE
renamed packages to be more descriptive

### PR DESCRIPTION
**Pull request by rabeyta**

### CODE REVIEW

**Comment by SpottedOtter** [comment]
Great work, Robert!

Valerie

Sent from my iPad

On Dec 30, 2015, at 15:03, Robert Abeyta <notifications@github.com> wrote:

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2
Commit Summary

   - renamed packages to be more descriptive

File Changes

   - *M* mutation-runner-plugin/META-INF/MANIFEST.MF
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-0>
   (2)
   - *M* mutation-runner-plugin/plugin.xml
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-1>
   (8)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/Activator.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-2>
   (2)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/ConsoleManager.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-3>
   (2)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/Mutation.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-4>
   (2)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/exception/M2HomeNotSetException.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-5>
   (2)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/handlers/ExecutePITTest.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-6>
   (12)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/maven/ExecuteMaven.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-7>
   (4)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/preferences/MutationRunnerPreferencePage.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-8>
   (4)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/preferences/PreferenceConstants.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-9>
   (2)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/preferences/PreferenceInitializer.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-10>
   (4)
   - *R*
   mutation-runner-plugin/src/main/java/com/statefarm/mutationrunner/preferences/PreferenceUtils.java
   <https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2/files#diff-11>
   (4)

Patch Links:

   -
   https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2.patch
   -
   https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/StateFarmIns/mutation-runner-eclipse-plugin/pull/2>.

**Comment by DylanLWScott** [comment]
Do you think the first part should be com.statefarmins to match our Org?

**Comment by rabeyta** [comment]
@DylanLWScott I personally like it matching the actual name of the company and not the org. It being a valid company domain is a plus as it falls under the normal java package naming conventions. I also think it would remove any ambiguity down the road on where it came from. I'm open to changing though if you feel strong about it.

**Comment by DylanLWScott** [comment]
Agree :+1:

**Pull request merged**
